name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-22.04]
        include:
          # single mac test due to minute multipliers
          # https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
          - node: 18
            os: macos-12
          # single windows test due to node.js 14 node-gyp / vs 2022 issues
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install node-gyp deps
        run: sudo apt-get install -y autoconf make libtool automake
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
