name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-22.04]
        include:
          - node: 16
            os: macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install node-gyp deps
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            sudo apt-get install -y autoconf make libtool automake tree
          else
            brew install autoconf automake libtool
          fi
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run configure
      - run: npm ci
      - run: tree
      - run: npm run build --if-present
      - run: tree
      - run: npm test
